### ISSUE TITLE
Add usage example

### ISSUE THREAD

**Issue by souzatharsis** [mo-haggag/ROG#1]
I am interested in integrating ROG with `podcastfy.ai` to enable generation of long-form podcasts.

The following would be helpful as 'usage example':

1. How to setup ROG
2. ROG's interface (input <> output)
3. how to use/config Stop Sequence token
4. How to use different base models, e.g. Gemini instead of OpenAI

Well done and thanks for sharing your work.

**Comment by mo-haggag** [comment]
@souzatharsis, have you checked [ROG.py](https://github.com/mo-haggag/ROG/blob/main/ROG.py)? It contains a complete example. You might want to look at [this function](https://github.com/mo-haggag/ROG/blob/e7433fb868d2902bcdbd30d9e300f711a86b2629/ROG.py#L160) specifically.

To use ROG with other models, you can simply follow a structure similar to the provided example. Depending on your model of choice, you will need to standardize how system and user messages are created and update the lines related to how the model is [called](https://github.com/mo-haggag/ROG/blob/e7433fb868d2902bcdbd30d9e300f711a86b2629/ROG.py#L89-L90).
